name: fat_markdown_example
description: Demonstrates how to use the fat_markdown package.
publish_to: 'none'

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  fat_markdown:
    path: ../

  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/mds/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: packages/fat_markdown/fonts/RobotoMono-Regular.ttf
        - asset: packages/fat_markdown/fonts/RobotoMono-Bold.ttf
          weight: 700