name: fat_markdown
description: A powerful Flutter Markdown widget with LaTeX math and syntax highlighting.
version: 0.9.1
homepage: https://damphat.github.io/fat_markdown/
repository: https://github.com/damphat/fat_markdown
issue_tracker: https://github.com/damphat/fat_markdown/issues

topics:
  - markdown
  - latex
  - syntax-highlighting
  - widget
  - ui

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  markdown: ^7.3.0
  syntax_highlight: ^0.5.0
  flutter_math_fork: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

