name: fat_markdown
description: A powerful Flutter Markdown widget with LaTeX math and syntax highlighting.
version: 0.9.0
homepage: https://github.com/damphat/fat_markdown

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  markdown: ^7.3.0
  syntax_highlight: ^0.5.0
  flutter_math_fork: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

